### ISSUE TITLE
Update demos/2019_07_Hackfest so that a user who has their own existing OCP 3 and 4 environments can still follow instructions to migrate applications

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/mig-agnosticd#33]
https://github.com/fusor/mig-agnosticd/tree/master/demos/2019_07_Hackfest

We need to extend the docs so that a user with an OCP 3, 4 clusters not provisioned from mig-agnosticd can still use our docs to walk through lab.

Let's capture the manual steps for:
 - Deploying mig-operator
 - Creating SA on source cluster
 - Configure CORS on source
 - Deploying sample apps

**Comment by pranavgaikwad** [comment]
stale or already addressed
