### ISSUE TITLE
Need to ensure that  mssql-scc.yaml file is present in labs

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/mig-agnosticd#59]
I don't think we have the mssql-scc.yaml file included with the lab files.

https://github.com/fusor/mig-agnosticd/blob/master/demos/2019_RHTE/labs/5.md#511-create-mssql-security-context-constraint

```
$ oc create -f mssql-scc.yaml
securitycontextconstraints.security.openshift.io/mssql-persistent-scc created
```

We have a copy https://github.com/fusor/mig-agnosticd/blob/master/demos/2019_07_Hackfest/files/mssql-scc.yaml

**Comment by tsanders-rh** [comment]
Yes, mssql-scc.yaml and sock-shop-scc.yaml will be included in my next PR.

**Comment by pranavgaikwad** [comment]
Stale or probably solved
