### ISSUE TITLE
Need to correct cors.yaml location in documentation

### ISSUE THREAD

**Issue by apinnick** [konveyor/mig-agnosticd#74]
https://github.com/fusor/mig-agnosticd/blob/master/demos/2019_RHTE/labs/2.md

Section 2.1, step 2 says this:

Run the following playbook to enable the proper CORS headers on the source v3.11 cluster. Be sure to provide the GUIDs for the 3.11 and 4.1 environments. The cors.yaml is in the lab-user's home directory (/home/lab-user).

The file is in /home/lab-user/lab_user/scripts.

**Comment by pranavgaikwad** [comment]
Fixed thru #78
