### ISSUE TITLE
You must reload the CAM-UI to force pv discovery at lab 6 - section 6.3

### ISSUE THREAD

**Issue by GeraldSP** [konveyor/mig-agnosticd#89]
During some manual lab testing I faced a simple but annoying bug in the product, it can generate confusion to the lab participants. 

If you come from the lab 5 (mssql migration) straightforward to the lab 6 and you don't reload the CAM-UI, the next migration plan will fail trying to discover the project's PVCs, it will only display the previous namespace PVCs (lab5) regardless of the current ns selecction.

I suggest to put a strongger note in the lab to avoid confusion, I will send a PR as soon as i can.

**Comment by pranavgaikwad** [comment]
Stale
