### ISSUE TITLE
Bump OCP4 version to something more recent than 4.2.0

### ISSUE THREAD

**Issue by eriknelson** [konveyor/mig-agnosticd#98]
ocp4_vars has the ocp version pegged to 4.2.0. Can we update this to a more recent release; either 4.2.12 (or latest z stream), or a 4.3 release if that's available now?

Also, does the osrelease var or repo_version need to change?

**Comment by pranavgaikwad** [comment]
Fixed through https://github.com/konveyor/mig-agnosticd/commit/c120b28d8564b735a576f4dce24791d713de5576
